#!/bin/bash


####TEST 1: Basic DP Test
#echo "Compiling variational dp test..."
#g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testdp.cpp -lboost_system -o testdp
#if [ -e "testdp" ]
#then
#    echo "Done compiling, running test..."
#	./testdp
#	rm testdp
#	mkdir dpresults
#	cp test/dpplot.py dpresults
#	mv *.log dpresults
#	echo "Done DP! Go to ./dpresults and run python dpplot.py to visualize the results."
#else
#    echo "Error experienced during compilation, test was not run."
#fi

####TEST 2: Basic HDP Test
#echo "Compiling variational hdp test..."
#g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testhdp.cpp -lboost_system -o testhdp
#if [ -e "testhdp" ]
#then
#    echo "Done! Running test..."
#	./testhdp
#	rm testhdp
#	mkdir hdpresults
#	cp test/hdpplot.py hdpresults
#	mv *.log hdpresults
#	echo "Done HDP! Go to ./hdpresults and run python hdpplot.py to visualize the results."
#else
#    echo "Error experienced during compilation, test was not run."
#fi


###TEST 3: DP Test with Non-standard prior
#echo "Compiling variational dp w/ nonstandard prior test..."
#g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testdpprior.cpp -lboost_system -o testdp
#if [ -e "testdp" ]
#then
#    echo "Done compiling, running test..."
#	./testdp
#	rm testdp
#	mkdir dpresults
#	cp test/dppriorplot.py dpresults
#	mv *.log dpresults
#	echo "Done DP nonstandard prior! Go to ./dpresults and run python dppriorplot.py to visualize the results."
#else
#    echo "Error experienced during compilation, test was not run."
#fi

####TEST 4: Thread pool test
#echo "Compiling pool test..."
#g++ -std=c++11 -O3 -I/usr/local/include test/testpool.cpp -lpthread -o testpool
#if [ -e "testpool" ]
#then
#    echo "Done compiling, running test..."
#	./testpool
#	rm testpool
#	echo "Done pool test!"
#else
#    echo "Error experienced during compilation, test was not run."
#fi
#
####TEST 5: Matching test
#echo "Compiling matching test..."
#g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testmatching.cpp -o testmatching
#if [ -e "testmatching" ]
#then
#    echo "Done compiling, running test..."
#	./testmatching
#	rm testmatching
#	echo "Done matching test!"
#else
#    echo "Error experienced during compilation, test was not run."
#fi


###TEST 6: SDA DP Test
#echo "Compiling sda dp test..."
#g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testsdadp.cpp -lboost_system -lpthread -o testsdadp
#if [ -e "testsdadp" ]
#then
#    echo "Done compiling, running test..."
#	./testsdadp
#	rm testsdadp
#	mkdir sdadpresults
#	cp test/sdadpplot.py sdadpresults
#	mv *.log sdadpresults
#	echo "Done SDA DP! Go to ./sdadpresults and run python sdadpplot.py to visualize the results."
#else
#    echo "Error experienced during compilation, test was not run."
#fi


#TEST 7: NIW Test
#echo "Compiling niw test..."
#g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testniw.cpp -lboost_system -lpthread -o testniw
#
#if [ -e "testniw" ]
#then
#    echo "Done compiling, running test..."
#	./testniw
#	rm testniw
#	mkdir niwresults
#	cp test/niwplot.py niwresults
#	echo "Done testing niw! Go to ./niwresults and run python niwplot.py to visualize the results."
#else
#    echo "Error experienced during compilation, test was not run."
#fi

#TEST 8: SDA DP Evaluation
echo "Compiling sda dp eval..."
g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/src/vb.c test/src/updates.c test/src/costfcn.c test/src/vbfuncs_gaussian.c test/evalsdadp.cpp -lboost_system -lpthread -lgsl -lblas -lrt -o evalsdadp
if [ -e "evalsdadp" ]
then
    echo "Done compiling, running test..."
	./evalsdadp
	rm evalsdadp
	mkdir sdaresults
	cp test/plotevalsdadp.py sdaresults
	mv *.log sdaresults
	echo "Done SDA DP Evaluation! Go to ./sdaresults and run python plotevalsdadp.py to visualize the results."
else
    echo "Error experienced during compilation, test was not run."
fi

#TEST 9: MNIST Evaluation
echo "Compiling mnist eval..."
g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/src/vb.c test/src/updates.c test/src/costfcn.c test/src/vbfuncs_gaussian.c test/evalmnist.cpp -lboost_system -lpthread -lgsl -lblas -lrt -o evalmnist
if [ -e "evalmnist" ]
then
    echo "Done compiling, running test..."
	./evalmnist
	rm evalmnist
	mkdir mnistresults
	cp test/evalMNIST.py mnistresults
	mv *.log mnistresults
	echo "Done MNIST Evaluation! Go to ./mnistresults and run python evalMNIST.py to visualize the results."
else
    echo "Error experienced during compilation, test was not run."
fi

#TEST 9: SUN Evaluation
echo "Compiling sun eval..."
g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/src/vb.c test/src/updates.c test/src/costfcn.c test/src/vbfuncs_gaussian.c test/evalsun.cpp -lboost_system -lpthread -lgsl -lblas -lrt -o evalsun
if [ -e "evalsun" ]
then
    echo "Done compiling, running test..."
	./evalsun
	rm evalsun
	mkdir sunresults
	cp test/evalSUN.py sunresults
	mv *.log sunresults
	echo "Done SUN Evaluation! Go to ./sunresults and run python evalSUN.py to visualize the results."
else
    echo "Error experienced during compilation, test was not run."
fi


