#!/bin/bash


####TEST 1: Basic DP Test
#echo "Compiling variational dp test..."
#g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testdp.cpp -lboost_system -o testdp
#if [ -e "testdp" ]
#then
#    echo "Done compiling, running test..."
#	./testdp
#	rm testdp
#	mkdir dpresults
#	cp test/dpplot.py dpresults
#	mv *.log dpresults
#	echo "Done DP! Go to ./dpresults and run python dpplot.py to visualize the results."
#else
#    echo "Error experienced during compilation, test was not run."
#fi

####TEST 2: Basic HDP Test
#echo "Compiling variational hdp test..."
#g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testhdp.cpp -lboost_system -o testhdp
#if [ -e "testhdp" ]
#then
#    echo "Done! Running test..."
#	./testhdp
#	rm testhdp
#	mkdir hdpresults
#	cp test/hdpplot.py hdpresults
#	mv *.log hdpresults
#	echo "Done HDP! Go to ./hdpresults and run python hdpplot.py to visualize the results."
#else
#    echo "Error experienced during compilation, test was not run."
#fi


###TEST 1: DP Test with Non-standard prior
echo "Compiling variational dp test..."
g++ -std=c++11 -O3 -I/usr/local/include/eigen3 -I/usr/local/include test/testdpprior.cpp -lboost_system -o testdp
if [ -e "testdp" ]
then
    echo "Done compiling, running test..."
	./testdp
	rm testdp
	mkdir dpresults
	cp test/dppriorplot.py dpresults
	mv *.log dpresults
	echo "Done DP! Go to ./dpresults and run python dppriorplot.py to visualize the results."
else
    echo "Error experienced during compilation, test was not run."
fi

